Break out conda management
uwhackweek/jupyterbook-template pull request #43
Opened 2022-01-06 19:24 UTC by jomey

Create a dedicated folder to manage the conda environment and associated lock files.
Beefed up the `lock-environment.sh` file a bit and added some checks.

2022-01-06 19:28 UTC, jomey commented
I haven't run the script to generate new lock files. There are quite a few more changes other than adding the `cookiecutter`
Want to create a separate PR to better review them and be able to revert.
Then I would also need someone with a Mac to test the .lock file for that platform

2022-01-06 21:50 UTC, JessicaS11 commented on CONTRIBUTING.md
> +   __NOTE__: If you're running linux or Windows use `binder/conda-linux-64.lock`
```suggestion
   __NOTE__: If you're running linux or Windows use `conda/conda-linux-64.lock`
```

2022-01-06 21:51 UTC, JessicaS11 requested changes
See comment - otherwise looks good to me!

2022-01-07 14:39 UTC, jomey commented
Going to wait until PR #44 is in to test this against the updated GH Actions

2022-01-07 15:48 UTC, JessicaS11 approved these changes

2022-01-07 17:19 UTC, jomey commented
Checks for test are failing and include this error:
```
./scripts/deploy_website.sh: line 24: cookiecutter: command not found
```
As mentioned above in a comment, I will follow up with a separate PR to update the lock files and add cookiecutter.

2022-01-07 17:20 UTC, scottyhq commented
> As mentioned above in a comment, I will follow up with a separate PR to update the lock files and add cookiecutter. 

Sounds good. I think you'd be fine adding the new lockfiles in this PR as well. up to you! merge whenever.

2022-01-07 17:21 UTC, jomey commented
Here another error from the test run:
```
Setup auth token
  Error: Action failed with "not found deploy key or tokens"
```
Log an issue?

2022-01-07 17:23 UTC, merged

2022-01-07 17:28 UTC, scottyhq commented
> Error: Action failed with "not found deploy key or tokens" 

Looks like GitHub actions checks the step *inputs* even if the step does not run. I'm surprised it raises an error, if we want to avoid it, we could pass the default token for any steps that run `buildbook` but do not publish:

```
    - uses: ./.github/actions/buildbook
      with:
        jb-cache: true
        publish-to-gh: true
        jb-save: true
        token:  ${{ secrets.GITHUB_TOKEN }}
```

As in https://github.com/uwhackweek/jupyterbook-template/blob/a9d26cfa325291b5b5f1d63cea9d0085de8844d5/.github/workflows/deploy.yaml#L22

2022-01-07 17:48 UTC, jomey commented
Alternatively we could also access the input context via `index syntax':
```
inputs['token']
```

This should not raise an error and I can see whey the 'property dereference' syntax throws an error.

https://docs.github.com/en/actions/learn-github-actions/contexts#about-contexts

2022-01-07 18:12 UTC, jomey commented
> interesting. wouldn't using the 'index syntax' still raise an error if 'token' doesn't exist? maybe just give the 'token' input an empty string default value: `default: ' '` ?

Depends what GitHub is using for interpreting the syntax. Ruby would return a `nil` value, while Python raises a key error.
I will open a PR and test this.